version: '2'
services:
  postgres:
    image: 'postgres:9.6.9-alpine'
    environment:
      POSTGRES_PASSWORD: 12345678a
      POSTGRES_USER: postgres
      POSTGRES_DB: djps
    volumes:
    - './docker_data/pg:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  webapp:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/code
    ports:
      - '8000:8000'